### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by Mixu78**
This fixes some minor grammatical errors in the README of the project, and adds more explanations to some sections of the README.

### CODE REVIEW

**Comment by lajp** [comment]
Nice! please do also change the "issues" link on the last line to point to this new repo-location (under the Testausserveri organization)

And also while you're at it, Could you add a part to the "Hosting" section where you describe the necessary permission-scopes that are required on-invite in order for the bot to be able to initialize application commands on the hosts guild-of-selection.

Here's a picture of the necessary scopes:
image

Otherwise this looks good, and it's definitely an improvement over the previous one. :)

**Comment by romeq** [comment]
Also, wouldn't it make sense to call "vahti"s something else, such as "watchers"? Would make more sense for non-finns.

**Comment by lajp** [comment]
@romeq I don't think so, The choice to use the word "Vahti" was quite deliberate on my part. And also, we do not support other languages than Finnish anyways, so I don't really see a point in not using the term + all of the end-users (AFAIK) are Finns.

**Comment by romeq** [comment]
If the whole project doesn't support any other language than finnish, why are we even speaking english in the first place? :p

**Comment by lajp** [comment]
It's good practice since most of the "technical" world is run in English. In my opinion it would be more difficult to talk about code in Finnish because I (and the Finnish language) lack(s) the terminology for a lot of things.

**Comment by romeq** [comment]
Fair enough.

**Comment by ahnl** [comment]
An `.example.env` could be handy to add, as it currently takes a bit of time to copy the variable keys by hand to a new file. 

Roni has developed an useful tool by name env-exampler to generate the file from a `.env` file, so just run `npx env-exampler` and push the changes.

**Comment by romeq** [comment]
@ahnl Sounds good. Though, this pull request was for README.md as shown in the title.

Could that possibly be made in another pull request, just to keep things organized?

**Comment by ahnl** [comment]
How ever you want to. Imo its related to documentation, so can keep in this PR as well.

**Comment by lajp** [comment]
Is there some way this merge could be redirected to the `main` branch instead of `next`? I think it makes no sense to merge this to the `next` branch since it only consists of improvements to the documentation and doesn't document any features that are exclusive to the `next` branch.

**Comment by Mixu78** [comment]
Changed to target `main`

**Comment by lajp** [comment]
This now looks good to me. I'll be merging this shortly and adding the requested `.env.example` in another commit.

**Pull request merged**
